preprocessing:
  patch_sizes: [512, 256, 128]
  overlap_ratio: 0.25
  sigma_threshold: 3.0

euclid:
  reference_pixel_method: "kubik_optimal"
  optimal_x: 64
  optimal_y: 4

case:
  dual_detector: true
  extra_columns: 8
  total_frames: 450

storage:
  compression: "lzf"
  chunk_size: 512

cache:
  root_dir: "data/processed" 
  validation_enabled: true

logging:
  level: "INFO"
  file: "results/preprocessing.log"
  
data:
  raw_root: "/proj/case/2025-06-05"
  processed_root: "data/processed"
  interim_root: "data/interim"