preprocessing:
  patch_sizes: [512, 256, 128]
  overlap_ratio: 0.25
  sigma_threshold: 3.0

euclid:
  optimal_x: 64
  optimal_y: 4

case:
  optimal_x: 64
  optimal_y: 4
  dual_detector: true
  extra_columns: 8
  total_frames: 450

storage:
  compression: "lzf"
  chunk_size: 512

cache:
  root_dir: "/projects/JWST_planets/ilongo/processed_data" 
  validation_enabled: true

logging:
  level: "INFO"
  file: "results/preprocessing.log"
  
data:
  raw_root: "/projects/JWST_planets/ilongo/raw_data"
  processed_root: "/projects/JWST_planets/ilongo/processed_data"
  interim_root: "/projects/JWST_planets/ilongo/interim_data"